# 必须保存为UTF-8格式
spring:
  profiles:
    active:
    - dev

---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: mc-config-dept-client-8001

spring:
  profiles: dev
   application:
    name: microservicecloud-dept
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver             # mysql驱动包
    url: jdbc:mysql://localhost:3306/wms                    # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 3000                                 # 等待连接获取的最大超时时间
      

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml    # mybatis配置文件所在路径
  type-aliases-package: com.blg.springboot.entities       # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件


#客户端注册进eureka服务列表内
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: microservicecloud-dept8001   #改线上名称
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: blg-microservicecloud
  company.name: www.blg.com
  build.artifactId: $project.artifactId$
  build.version: ${project.version}
  build.test: ${server.port}
 
---
server:
  port: 8001
spring:
  profiles: test
  application:
    name: mc-config-dept-client-8001

spring:
  profiles: dev
   application:
    name: microservicecloud-dept
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver             # mysql驱动包
    url: jdbc:mysql://localhost:3306/wms2                    # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 3000                                 # 等待连接获取的最大超时时间
      

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml    # mybatis配置文件所在路径
  type-aliases-package: com.blg.springboot.entities       # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件


#客户端注册进eureka服务列表内
eureka:
  client:
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: microservicecloud-dept8001   #改线上名称
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: blg-microservicecloud
  company.name: www.blg.com
  build.artifactId: $project.artifactId$
  build.version: ${project.version}
  build.test: ${server.port}